/*
 * jQuery Nivo Slider v2.7.1
 * http://nivo.dev7studios.com
 *
 * Copyright 2011, Gilbert Pellegrom
 * Free to use and abuse under the MIT license.
 * http://www.opensource.org/licenses/mit-license.php
 * 
 * January 2012
 */
(function(c,q){function s(){return function(){}}function z(p,t){function v(c){for(var d,e,a=c.length;a;d=parseInt(Math.random()*a),e=c[--a],c[a]=c[d],c[d]=e);return c}function o(a,d,e,b){var h=a.data("nivo:vars");if(h&&!h.stop||b){b?(b=="prev"&&a.css("background",'url("'+h.b.attr("src")+'") no-repeat'),b=="next"&&a.css("background",'url("'+h.b.attr("src")+'") no-repeat')):a.css("background",'url("'+h.b.attr("src")+'") no-repeat');h.a++;if(h.a==h.g)h.a=0;if(h.a<0)h.a=h.g-1;d=c(d[h.a]);h.b=d.is("img")?d:d.find("img").eq(0);e.o&&c(".nivo-controlNav a",
a).removeClass("active").eq(h.a).addClass("active");x(e);c(".nivo-slice",a).remove();c(".nivo-box",a).remove();b=e.k;e.k==="random"?(d=["sliceDownRight","sliceDownLeft","sliceUpRight","sliceUpLeft","sliceUpDown","sliceUpDownLeft","fold","fade","boxRandom","boxRain","boxRainReverse","boxRainGrow","boxRainGrowReverse"],b=d[Math.floor(Math.random()*(d.length-1))]):e.k.indexOf(",")!==-1&&(d=e.k.split(","),b=d[Math.floor(Math.random()*d.length)]);h.b.attr("data-transition")&&(b=h.b.attr("data-transition"));
h.f=!0;h=function(b,c,d,f,h){setTimeout(function(){b.animate(c,!d?e.d:d,"",h?function(){a.trigger("nivo:animFinished")}:q)},100+f)};switch(b){case "sliceDown":case "sliceDownRight":case "sliceDownLeft":r();var d=0,f=c(".nivo-slice",a),k=0;b==="sliceDownLeft"&&(f=f.j());do b=c(f[k]),b.css({top:"0px"}),h(b,{height:"100%",opacity:1},q,d,k===e.c-1?!0:!1),d+=50;while(++k<e.c);break;case "sliceUp":case "sliceUpRight":case "sliceUpLeft":r();d=0;f=c(".nivo-slice",a);k=0;b==="sliceUpLeft"&&(f=f.j());do b=
c(f[k]),b.css({bottom:"0px"}),h(b,{height:"100%",opacity:1},q,d,k===e.c-1?!0:!1),d+=50;while(++k<e.c);break;case "sliceUpDown":case "sliceUpDownRight":case "sliceUpDownLeft":r();var l=d=0,f=c(".nivo-slice",a),k=0;b==="sliceUpDownLeft"&&(f=f.j());do b=c(f[k]),l?b.css("top","0px"):b.css("bottom","0px"),l=!l,h(b,{height:"100%",opacity:1},q,d,k===e.c-1?!0:!1),d+=50;while(++k<e.c);break;case "fold":r();d=0;f=c(".nivo-slice",a);l=k=0;do b=c(f[k]),l=b.width(),b.css({top:"0px",height:"100%",width:"0px"}),
h(b,{width:l+"px",opacity:1},q,d,k===e.c-1?!0:!1),d+=50;while(++k<e.c);break;default:case "fade":r();var m=c(".nivo-slice",a).eq(0);m.css({height:"100%",width:a.width()+"px"}).animate({opacity:1},e.d*2,"",function(){a.trigger("nivo:animFinished")});break;case "slideInRight":r();m=c(".nivo-slice",a).eq(0);m.css({height:"100%",width:"0px",opacity:1}).animate({width:a.width()+"px"},e.d*2,"",function(){a.trigger("nivo:animFinished")});break;case "slideInLeft":r();m=c(".nivo-slice",a).eq(0);m.css({height:"100%",
width:"0px",opacity:1,left:"",right:"0px"}).animate({width:a.width()+"px"},e.d*2,"",function(){m.css({left:"0px",right:""});a.trigger("nivo:animFinished")});break;case "boxRandom":y();var f=e.e*e.h,d=0,g=v(c(".nivo-box",a)),j=0;do l=c(g[j]),h(l,{opacity:1},q,d,j===f-1?!0:!1),d+=20;while(++j<f);break;case "boxRain":case "boxRainReverse":case "boxRainGrow":case "boxRainGrowReverse":y();var f=e.e*e.h,d=0,k=[],i=l=0,g=c(".nivo-box",a),j=0;if(b=="boxRainReverse"||b=="boxRainGrowReverse")g=g.j();k[l]=[];
do k[l][i]=g[j],++i,i===e.e&&(++l,k[l]=[],i=0);while(++j<f);var n=i=j=g=0,o=0,p=0;do{i=g;do++n,i>=0&&i<e.e&&(l=c(k[j][i]),o=l.width(),p=l.height(),(b=="boxRainGrow"||b=="boxRainGrowReverse")&&l.width(0).height(0),h(l,{width:o,height:p,opacity:1},e.d/1.3,d,n===f?!0:!1)),--i;while(++j<e.h);j=0;d+=100}while(++g<e.e*2)}}}function y(){var j=b.width(),d=Math.round(j/a.e),e=Math.round(b.height()/a.h),g=document.createDocumentFragment(),h=0,i=0,k=0,l={background:'url("'+f.b.attr("src")+'") no-repeat',backgroundPosition:"",
left:"",top:"",width:"",height:e+"px",opacity:0};do{l.top=e*i+"px";l.width=d+"px";do{h=d*k;l.left=d*k+"px";l.backgroundPosition="-"+(d+h-d)+"px -"+(e+i*e-e)+"px";if(k===a.e-1)l.width=j-h+"px";g.appendChild(c('<div class="nivo-box"></div>').css(l)[0])}while(++k<a.e);k=0}while(++i<a.h);b.append(g)}function r(){var j=f.b.attr("src"),d=b.width(),e=0,i=document.createDocumentFragment(),h,g,k={background:"",left:"",width:"",height:"0px",opacity:0};do{h=Math.round(d/a.c);g=h*e;k.left=g+"px";k.background=
'url("'+j+'") no-repeat -'+(h+g-h)+"px 0%";k.width=h+"px";if(e==a.c-1)k.width=d-g+"px";i.appendChild(c('<div class="nivo-slice"></div>').css(k)[0])}while(++e<a.c);b.append(i)}function x(a){var d=c(".nivo-caption",b),e=f.b.attr("title")?f.b.attr("title"):"";e?(e.substr(0,1)=="#"&&(e=c(e).html()),d.css("opacity")!=0?d.find("p").stop().fadeTo(a.d,0,function(){c(this).html(e).stop().fadeTo(a.d,1)}):d.find("p").html(e),d.stop().fadeTo(a.d,a.n)):d.stop().fadeTo(a.d,0)}var a=c.extend({},c.fn.nivoSlider.u,t),f={a:0,
b:"",g:0,f:!1,paused:!1,stop:!1},b=c(p);b.data("nivo:vars",f);b.css("position","relative");b.addClass("nivoSlider");for(var m=b.children(),n=m.length,g,i=0,u=0,w=q;--n+1;)g=c(m[n]),g.is("img")||(g.is("a")&&(g.addClass("nivo-imageLink"),w=g),g=g.find("img").eq(0)),i=g.width(),u=g.height(),i===0&&(i=g.attr("width")),u===0&&(u=g.attr("height")),i>b.width()&&b.width(i),u>b.height()&&b.height(u),w&&w.css("display","none"),g.css("display","none"),++f.g;if(a.D)a.i=Math.floor(Math.random()*f.g);if(a.i>0){if(a.i>=
f.g)a.i=f.g-1;f.a=a.i}n=c(m[f.a]);f.b=n.is("img")?n:n.find("img").eq(0);n.is("a")&&n.css("display","block");b.css("background",'url("'+f.b.attr("src")+'") no-repeat');b.append(c('<div class="nivo-caption"><p></p></div>').css({display:"none",opacity:a.n}));c(".nivo-caption",b).css("opacity",0);x(a);var j=0;!a.l&&m.length>1&&(j=setInterval(function(){o(b,m,a,!1)},a.m));a.v&&(b.append('<div class="nivo-directionNav"><a class="nivo-prevNav">'+a.C+'</a><a class="nivo-nextNav">'+a.A+"</a></div>"),a.w&&
(c(".nivo-directionNav",b).hide(),b.hover(function(){c(".nivo-directionNav",b).show()},function(){c(".nivo-directionNav",b).hide()})),c("a.nivo-prevNav",b).live("click",function(){if(f.f)return!1;clearInterval(j);j="";f.a-=2;o(b,m,a,"prev")}),c("a.nivo-nextNav",b).live("click",function(){if(f.f)return!1;clearInterval(j);j="";o(b,m,a,"next")}));if(a.o){n=c('<div class="nivo-controlNav"></div>');i="";g=0;b.append(n);do a.q?(i=m.eq(g),i.is("img")||(i=i.find("img").eq(0)),i=a.r?'<img src="'+i.attr("rel")+
'" alt="" />':'<img src="'+i.attr("src").replace(a.t,a.s)+'" alt="" />'):i=g+1,n.append('<a class="nivo-control" rel="'+g+'">'+i+"</a>");while(++g<m.length);c(".nivo-controlNav a",b).eq(f.a).addClass("active");c(".nivo-controlNav a",b).live("click",function(){var g=c(this);if(f.f||g.hasClass("active"))return!1;clearInterval(j);j="";b.css("background",'url("'+f.b.attr("src")+'") no-repeat');f.a=g.attr("rel")-1;o(b,m,a,"control")})}a.z&&c(window).keypress(function(c){if(c.keyCode=="37"){if(f.f)return!1;
clearInterval(j);j="";f.a-=2;o(b,m,a,"prev")}if(c.keyCode=="39"){if(f.f)return!1;clearInterval(j);j="";o(b,m,a,"next")}});a.B&&b.hover(function(){f.paused=!0;clearInterval(j);j=q},function(){f.paused=!1;j===q&&!a.l&&(j=setInterval(function(){o(b,m,a,!1)},a.m))});b.bind("nivo:animFinished",function(){f.f=!1;for(var g,d=m.length,e=c(m[f.a]);--d+1;)g=c(m[d]),g.is("a")&&g.css("display","none");e.is("a")&&e.css("display","block");j==""&&!f.paused&&!a.l&&(j=setInterval(function(){o(b,m,a,!1)},a.m))});this.stop=
function(){if(!c(p).data("nivo:vars").stop)c(p).data("nivo:vars").stop=!0};this.start=function(){if(c(p).data("nivo:vars").stop)c(p).data("nivo:vars").stop=!1};return this}c.fn.nivoSlider=function(p){return this.each(function(){var t=c(this);if(t.data("nivoslider"))return t.data("nivoslider");var v=new z(this,p);t.data("nivoslider",v)})};c.fn.nivoSlider.u={k:"random",c:15,e:8,h:4,d:500,m:3E3,i:0,v:!0,w:!0,o:!0,q:!1,r:!1,t:".jpg",s:"_thumb.jpg",z:!0,B:!0,l:!1,n:0.8,C:"Prev",A:"Next",D:!1,H:s(),F:s(),J:s(),I:s(),G:s()};
c.fn.j=[].reverse})(jQuery,null);