/**
* jQuery Nivo Slider v2.7.1
* http://nivo.dev7studios.com
*
* Copyright 2011, Gilbert Pellegrom
* Free to use and abuse under the MIT license.
* http://www.opensource.org/licenses/mit-license.php
*
* January 2012
*/
(function(e){var o=null;function s(){return function(){}}function z(v,t){function w(a){for(var b,d,e=a.length;e;b=parseInt(Math.random()*e),d=a[--e],a[e]=a[b],a[b]=d);return a}function p(c){var i=a.a.data("nivo:vars");if(i&&!i.stop||c){a.a.css("background",'url("'+i.d.url+'") no-repeat');++i.c;if(i.c>=i.i)i.c=0;else if(i.c<0)i.c=i.i-1;a.O=a.b;a.b=e(a.h[i.c]);a.b=a.b.is("img")?a.b:a.b.find("img").eq(0);i.N={url:a.O.attr("src")};i.d={url:a.b.attr("src"),title:a.b.attr("title"),A:a.b.data("transition")};b.v&&a.z.removeClass("active").eq(i.c).addClass("active");
x();e(".nivo-slice",a.a).remove();e(".nivo-box",a.a).remove();var d=b.o||"fade";b.o==="random"?(d=["sliceDownRight","sliceDownLeft","sliceUpRight","sliceUpLeft","sliceUpDown","sliceUpDownLeft","fold","fade","cycle","boxRandom","boxRain","boxRainReverse","boxRainGrow","boxRainGrowReverse"],d=d[Math.floor(Math.random()*(d.length-1))]):b.o.indexOf(",")!==-1&&(d=b.o.split(","),d=d[Math.floor(Math.random()*d.length)]);if(i.d.A)d=i.d.A;i.m=!0;var f=function(c,d,e,f,g){setTimeout(function(){c.animate(d,
e||b.e,"",g&&function(){a.a.trigger("nivo:animFinished")})},100+f)};switch(d){case "sliceDown":case "sliceDownRight":case "sliceDownLeft":r();var c=0,k=e(".nivo-slice",a.a),j=0,g;d==="sliceDownLeft"&&(k=k.n());do g=e(k[j]),g.css({top:"0"}),f(g,{height:"100%",opacity:1},o,c,j===b.f-1?!0:!1),c+=50;while(++j<b.f);break;case "sliceUp":case "sliceUpRight":case "sliceUpLeft":r();c=0;k=e(".nivo-slice",a.a);j=0;d==="sliceUpLeft"&&(k=k.n());do g=e(k[j]),g.css({bottom:"0"}),f(g,{height:"100%",opacity:1},o,
c,j===b.f-1?!0:!1),c+=50;while(++j<b.f);break;case "sliceUpDown":case "sliceUpDownRight":case "sliceUpDownLeft":r();var l=c=0,k=e(".nivo-slice",a.a),j=0;d==="sliceUpDownLeft"&&(k=k.n());do g=e(k[j]),l?g.css("top","0"):g.css("bottom","0"),l=!l,f(g,{height:"100%",opacity:1},o,c,j===b.f-1?!0:!1),c+=50;while(++j<b.f);break;case "fold":r();c=0;k=e(".nivo-slice",a.a);d=j=0;do g=e(k[j]),d=g.width(),g.css({top:"0",height:"100%",width:"0"}),f(g,{width:d+"px",opacity:1},o,c,j===b.f-1?!0:!1),c+=50;while(++j<
b.f);break;default:case "fade":r(1);g=e(".nivo-slice",a.a);g.css({width:a.a.width()+"px",height:"100%"}).animate({opacity:1},b.e*2,"",function(){a.a.trigger("nivo:animFinished")});break;case "cycle":case "cycleLeft":case "cycleRight":r(1);f=a.a.width();g=e(".nivo-slice",a.a);d=d==="cycleLeft"||d==="cycle"&&(c==="prev"||c==="control"&&i.c<i.l)?!0:!1;j=document.createDocumentFragment();c={position:"absolute",right:d?"0":f+"px",background:'url("'+i.N.url+'")',width:f+"px",height:"100%"};k={position:"absolute",
right:d?f+"px":"0",backgroundImage:'url("'+i.d.url+'")',width:f+"px",height:"100%"};j.appendChild(e("<div></div>").css(c)[0]);j.appendChild(e("<div></div>").css(k)[0]);g.html(j);c={left:d?-f+"px":"0",width:f*2+"px",height:"100%",opacity:1};g.css(c).animate({left:d?"0":-f+"px"},b.e*2,"",function(){a.a.trigger("nivo:animFinished")});break;case "slideInHorizontal":case "slideInLeft":case "slideInRight":r(1);g=e(".nivo-slice",a.a);d=d==="slideInLeft"||d==="slideInHorizontal"&&(c==="prev"||c==="control"&&
i.c<i.l)?!0:!1;c={left:d?"0":"",right:d?"":"0",backgroundPosition:d?"100% 0":"0 0",width:"0",height:"100%",opacity:1};g.css(c).animate({width:"100%"},b.e*2,"",function(){a.a.trigger("nivo:animFinished")});break;case "slideInVertical":case "slideInTop":case "slideInBottom":r(1);g=e(".nivo-slice",a.a);d=d==="slideInTop"||d==="slideInVertical"&&(c==="prev"||c==="control"&&i.c>i.l)?!0:!1;c={top:d?"0":"",bottom:d?"":"0",backgroundPosition:d?"0 100%":"0 0",width:"100%",height:"0",opacity:1};g.css(c).animate({height:"100%"},
b.e*2,"",function(){a.a.trigger("nivo:animFinished")});break;case "boxRandom":y();g=b.g*b.k;var c=0,h=w(e(".nivo-box",a.a)),m=0;do l=e(h[m]),f(l,{opacity:1},o,c,m===g-1?!0:!1),c+=20;while(++m<g);break;case "boxRain":case "boxRainReverse":case "boxRainGrow":case "boxRainGrowReverse":y();g=b.g*b.k;var c=0,k=[],n=l=0,h=e(".nivo-box",a.a),m=0,j=g;if(d=="boxRainReverse"||d=="boxRainGrowReverse")h=h.n();k[l]=[];do k[l][n]=h[m],++n,++m,n===b.g&&(++l,k[l]=[],n=0);while(--j);var p=j=n=m=h=0,q=0;do{n=h;do n>=
0&&n<b.g&&(l=e(k[m][n]),p=l.width(),q=l.height(),(d=="boxRainGrow"||d=="boxRainGrowReverse")&&l.width(0).height(0),f(l,{width:p,height:q,opacity:1},b.e/1.3,c,++j===g?!0:!1)),--n;while(++m<b.k);m=0;c+=100}while(++h<b.g*2)}i.l=i.c}}function y(){var c=a.a.width(),i=Math.round(c/b.g),d=Math.round(a.a.height()/b.k),h=document.createDocumentFragment(),k=0,j=0,g=0,l={background:'url("'+f.d.url+'") no-repeat',backgroundPosition:"",left:"",top:"",width:"",height:d+"px",opacity:0};do{l.top=d*j+"px";l.width=
i+"px";do{k=i*g;l.left=k+"px";l.backgroundPosition="-"+(i+k-i)+"px -"+(d+j*d-d)+"px";if(g===b.g-1)l.width=c-k+"px";h.appendChild(e('<div class="nivo-box"></div>').css(l)[0])}while(++g<b.g);g=0}while(++j<b.k);a.a.append(h)}function r(c){var i=f.d.url,d=a.a.width(),h=0,c=c||b.f,k=document.createDocumentFragment(),j,g,l={background:"",left:"",width:"",height:"0",opacity:0};do{j=Math.round(d/c);g=j*h;l.left=g+"px";l.background='url("'+i+'") no-repeat -'+(j+g-j)+"px 0%";l.width=j+"px";if(h===c-1)l.width=
d-g+"px";k.appendChild(e('<div class="nivo-slice"></div>').css(l)[0])}while(++h<c);a.a.append(k)}function x(){var c=f.d.title||o;c&&(c.substr(0,1)=="#"&&(c=e(c).html()),a.p.css("opacity")!=0?a.t.stop().fadeTo(b.e,0,function(){a.t.html(c).stop().fadeTo(b.e,1)}):a.t.html(c));a.p.stop().fadeTo(b.e,c?b.u:0)}var b=e.extend({},e.fn.nivoSlider.G,t),f={l:0,c:0,d:{},i:0,m:!1,paused:!1,stop:!1},a={};a.a=e(v);a.a.data("nivo:vars",f);a.a.css("position","relative");a.a.addClass("nivoSlider");a.h=a.a.children();for(var h,
q=a.h.length,n=0,u=0;--q+1;)h=e(a.h[q]),h.is("img")||(h.is("a")&&h.addClass("nivo-imageLink"),h=h.find("img").eq(0)),n=h.width(),u=h.height(),n===0&&(n=h.attr("width")),u===0&&(u=h.attr("height")),n>a.a.width()&&a.a.width(n),u>a.a.height()&&a.a.height(u),h.css("display","none"),++f.i;if(b.P)b.j=Math.floor(Math.random()*f.i);if(b.j>0){if(b.j>=f.i)b.j=f.i-1;f.l=b.j-1;f.c=b.j}a.b=e(a.h[f.c]);a.b.is("img")?f.d={url:a.b.attr("src"),title:a.b.attr("title")}:(f.d=a.b.find("img").eq(0),f.d={url:f.d.attr("src"),
title:f.d.attr("title")});a.b.is("a")&&a.b.css("display","block");a.a.css("background",'url("'+f.d.url+'") no-repeat').append(e('<div class="nivo-caption"><p></p></div>').css({display:"none",opacity:b.u}));a.p=e(".nivo-caption",a.a);a.t=a.p.find("p");a.p.css("opacity",0);x();if(f.i<2)return!1;var m=o;b.r||(m=setInterval(function(){p(!1)},b.s));if(b.H)a.a.append('<div class="nivo-directionNav"><a class="nivo-prevNav" data-dir="prev">'+b.M+'</a><a class="nivo-nextNav" data-dir="next">'+b.K+"</a></div>"),
a.q=e(".nivo-directionNav",a.a),b.I&&(a.q.hide(),a.a.hover(function(){a.q.show()},function(){a.q.hide()})),a.q.children().click(function(){var a=e(this).data("dir")||"next";if(f.m)return!1;clearInterval(m);m=o;a==="prev"&&(f.c-=2);p(a)});if(b.v){h=q="";for(n=a.h.length;--n+1;)b.B?(h=e(a.h[n]),h.is("img")||(h=h.find("img").eq(0)),h=b.C?'<img src="'+h.attr("rel")+'" alt="" />':'<img src="'+h.attr("src").replace(b.F,b.D)+'" alt="" />'):h=n+1,q='<a class="nivo-control" data-slide="'+n+'">'+h+"</a>"+q;
a.a.append('<div class="nivo-controlNav">'+q+"</div>");a.Q=e(".nivo-controlNav",a.a);a.z=a.Q.find("a");a.z.click(function(){var c=e(this);if(f.m||c.hasClass("active"))return!1;clearInterval(m);m=o;a.a.css("background",'url("'+f.d.url+'") no-repeat');f.c=c.data("slide")-1;p("control")}).eq(f.c).addClass("active")}b.J&&e(document).keydown(function(a){a=a.keyCode||a.which;if(f.m)return!1;clearInterval(m);m=o;a===37||a===63234?(f.c-=2,p("prev")):(a===39||a===63235)&&p("next")});b.L&&a.a.hover(function(){f.paused=
!0;clearInterval(m);m=o},function(){f.paused=!1;m===o&&!b.r&&(m=setInterval(function(){p(!1)},b.s))});a.a.bind("nivo:animFinished",function(){f.m=!1;for(var c,h=a.h.length;--h+1;)c=e(a.h[h]),c.is("a")&&c.css("display","none");a.b.is("a")&&a.b.css("display","block");m===o&&!f.paused&&!b.r&&(m=setInterval(function(){p(!1)},b.s))});this.stop=function(){if(!a.a.data("nivo:vars").stop)a.a.data("nivo:vars").stop=!0};this.start=function(){if(a.a.data("nivo:vars").stop)a.a.data("nivo:vars").stop=!1};return this}
e.fn.nivoSlider=function(v){return this.each(function(){var t=e(this);if(t.data("nivoslider"))return t.data("nivoslider");var w=new z(this,v);t.data("nivoslider",w)})};e.fn.nivoSlider.G={o:"random",f:15,g:8,k:4,e:500,s:3E3,j:0,H:!0,I:!0,v:!0,B:!1,C:!1,F:".jpg",D:"_thumb.jpg",J:!0,L:!0,r:!1,u:0.8,M:"Prev",K:"Next",P:!1,T:s(),R:s(),V:s(),U:s(),S:s()};e.fn.n=[].reverse})(jQuery);